config/routes.rb
Rails.application.routes.draw do

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :send_mensalist_mail, only: [:edit, :create]
    resources :parks
    resources :services
    resources :mensalists
    resources :vehicles
    resources :cash_flows
    resources :maps
    resources :admins
  end

  devise_for :admins
  devise_for :members
  get 'home', to: 'home#index'
  root 'home#index'

end

app/models/mensalist.rb
class Mensalist < ActiveRecord::Base
	belongs_to :park

	after_save :check_payment_status_and_update
  after_save :check_tolerance_date

	enum payment_status: {
    unpaid: 1,
    paid: 2,
    debtor: 3
	}

  def check_tolerance_date
    tolerance_date = self.days_of_tolerance
    add_days = self.first_invoice_date + tolerance_date.days
    self.update_column(:first_invoice_date, add_days) 
  end

  def check_payment_status_and_update
    check_payment = self.payment_status

    if check_payment == "paid"
      old_invoice_date = self.check_tolerance_date
      old_date = self.first_invoice_date
      invoice_date = old_date + 1.month
      self.update_columns(first_invoice_date: invoice_date, payment_status: 1, days_of_tolerance: 0)
      
      if old_date > invoice_date
        self.update_column(payment_status: 3)
      end
    end
  end

  def mensalist_receipt_date
    self.first_invoice_date - 1.month
  end
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  
  def index
    @admins = Admin.all
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
  end

  # GET /admins/new
  def new
    @admin = Admin.new
    authorize @admin
  end

  # GET /admins/1/edit
  def edit
    @admin = Admin.find(params[:id])
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      redirect_to backoffice_admins_path, notice: "Administrador cadastrados com sucesso."
    else
      render :new
    end
  end

  # PATCH/PUT /admins/1
  # PATCH/PUT /admins/1.json
  def update
    @admin = Admin.find(params[:id])
    if @admin.update(admin_params)
      redirect_to backoffice_admins_path, notice: "Os dados do administrador foram atualizados com sucesso."
    else
      render :edit
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
  	@admin = Admin.find(params[:id])
  	if @admin.present?
    	@admin.destroy
		end
      redirect_to backoffice_admins_path, notice: "Os dados do administrador foram deletados com sucesso."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_params
      params.require(:admin).permit(:email, :password, :password_confirmation, :name, :role)
    end
end

app/controllers/backoffice/cash_flows_controller.rb
class Backoffice::CashFlowsController < BackofficeController

  def index
    @cash_flows = CashFlow.all
  end

  # GET /cash_flows/1
  # GET /cash_flows/1.json
  def show
  end

  # GET /cash_flows/new
  def new
    @cash_flow = CashFlow.new
  end

  # GET /cash_flows/1/edit
  def edit
    @cash_flow = CashFlow.find(params[:id])
  end

  # POST /cash_flows
  # POST /cash_flows.json
  def create
    @cash_flow = CashFlow.new(cash_flow_params)
    if @cash_flow.save
      redirect_to backoffice_cash_flows_path, notice: "Os dados do caixa foram cadastrados com sucesso."
    else
      render :new
    end
  end

  # PATCH/PUT /cash_flows/1
  # PATCH/PUT /cash_flows/1.json
  def update
    @cash_flow = CashFlow.find(params[:id])
    if @cash_flow.update(cash_flow_params)
      redirect_to backoffice_cash_flows_path, notice: "Os dados do caixa foram atualizados com sucesso."
    else
      render :edit
    end
  end

  # DELETE /cash_flows/1
  # DELETE /cash_flows/1.json
  def destroy
  	@cash_flow = CashFlow.find(params[:id])
  	if @cash_flow.present?
    	@cash_flow.destroy
		end
      redirect_to backoffice_cash_flows_path, notice: "Os dados do caixa foram deletados com sucesso."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cash_flow
      @cash_flow = CashFlow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cash_flow_params
      params.require(:cash_flow).permit(:entry_cash, :cash_outflow)
    end
end

app/controllers/backoffice/maps_controller.rb
class Backoffice::MapsController < ApplicationController	
	
  def index
  end
end

app/controllers/backoffice/mensalists_controller.rb
class Backoffice::MensalistsController < BackofficeController
  skip_before_action :authenticate_admin!, only: :show

  def index
    @mensalists = Mensalist.all
  end

  # GET /mensalists/1
  # GET /mensalists/1.json
  def show
    @mensalist = Mensalist.find(params[:id])
    @services = Service.select(:id, :price, :name)

    @selected_services = @mensalist.services.map{ |e| 
      JSON.parse(e).with_indifferent_access 
    }
    
    @selected_services_ids = @selected_services.map{ |e| e["id"] }
    render layout: "application"
  end

  # GET /mensalists/new
  def new
    @mensalist = Mensalist.new
    @services = Service.select(:id, :price, :name)

    @selected_services = @mensalist.services.map{ |e| 
      JSON.parse(e).with_indifferent_access 
    }

    @selected_services_ids = @selected_services.map{ |e| e["id"] } 
  end

  # GET /mensalists/1/edit
  def edit
    @mensalist = Mensalist.find(params[:id])
    @services = Service.select(:id, :price, :name)

    @selected_services = @mensalist.services.map{ |e| 
      JSON.parse(e).with_indifferent_access 
    }
    
    @selected_services_ids = @selected_services.map{ |e| e["id"] } 
  end

  # POST /mensalists
  # POST /mensalists.json
  def create
    @mensalist = Mensalist.new(mensalist_params)
    mensalist_params[:services] = Hash.new(mensalist_params[:services])
    if @mensalist.save
      redirect_to backoffice_mensalists_path, notice: "O Mensalista #{@mensalist.name} foi cadastrado com sucesso."
    else
      render :new
    end
  end

  # PATCH/PUT /mensalists/1
  # PATCH/PUT /mensalists/1.json
  def update
    @mensalist = Mensalist.find(params[:id])
    if @mensalist.update(mensalist_params)
      redirect_to backoffice_mensalists_path, notice: "O Mensalista #{@mensalist.name} foi atualizado com sucesso."
    else
      render :edit
    end
  end

  # DELETE /mensalists/1
  # DELETE /mensalists/1.json
  def destroy
  	@mensalist = Mensalist.find(params[:id])
  	if @mensalist.present?
    	@mensalist.destroy
  	end
      redirect_to backoffice_mensalists_path, notice: "O Mensalista #{@mensalist.name} foi deletado com sucesso."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mensalist
      @mensalist = Mensalist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mensalist_params
      params.require(:mensalist).permit(:name, :email, :price, :park_id, :days_of_tolerance, :past_invoice_date,:first_invoice_date, :plates, :car_seat_numbers, :payment_status, :services => [])
    end
end

app/controllers/backoffice/parks_controller.rb
class Backoffice::ParksController < BackofficeController
  
  def index
    @parks = Park.all
  end

  # GET /parks/1
  # GET /parks/1.json
  def show
  end

  # GET /parks/new
  def new
    @park = Park.new
  end

  # GET /parks/1/edit
  def edit
    @park = Park.find(params[:id])
  end

  # POST /parks
  # POST /parks.json
  def create
    @park = Park.new(park_params)
    if @park.save
      redirect_to backoffice_parks_path, notice: "estacionamentos cadastrados com sucesso."
    else
      render :new
    end
  end

  # PATCH/PUT /parks/1
  # PATCH/PUT /parks/1.json
  def update
    @park = Park.find(params[:id])
    if @park.update(park_params)
      redirect_to backoffice_parks_path, notice: "Os dados do estacionamento foram atualizados com sucesso."
    else
      render :edit
    end
  end

  # DELETE /parks/1
  # DELETE /parks/1.json
  def destroy
  	@park = Park.find(params[:id])
  	if @park.present?
    	@park.destroy
		end
      redirect_to backoffice_parks_path, notice: "Os dados do estacionamento foram deletados com sucesso."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_park
      @park = Park.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def park_params
      params.require(:park).permit(:park_name, :park_location, :operating_hours, :park_cnpj)
    end
end

app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController
  
  def edit
    @vehicle = Vehicle.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def create
    @id = params[:id]
    begin
      AdminMailer.send_message(current_admin, params[:'recipient-name'], params[:'subject-text'] , params[:'message-text']).deliver_now
    rescue 
      puts "DEU RUIM"
    end
    
    respond_to do |format|
      format.js
    end
  end

end

app/controllers/backoffice/send_mensalist_mail_controller.rb
class Backoffice::SendMensalistMailController < ApplicationController
  def edit
    @mensalist = Mensalist.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def create
    @id = params[:id]
    begin
      AdminMailer.send_message(current_admin, params[:'recipient-name'], params[:'subject-text'] , params[:'message-text']).deliver_now
    rescue 
      puts "DEU RUIM"
    end
    
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/backoffice/services_controller.rb
class Backoffice::ServicesController < BackofficeController

  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
    if @service.save
      redirect_to backoffice_services_path, notice: "O Serviço #{@service.name} foi cadastrado com sucesso."
    else
      render :new
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    @service = Service.find(params[:id])
    if @service.update(service_params)
      redirect_to backoffice_services_path, notice: "O Serviço #{@service.name} foi atualizado com sucesso."
    else
      render :edit
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
  	@service = Service.find(params[:id])
  	if @service.present?
    	@service.destroy
		end
      redirect_to backoffice_services_path, notice: "O Serviço #{@service.name} foi deletado com sucesso."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :price)
    end
end

app/controllers/backoffice/vehicles_controller.rb
class Backoffice::VehiclesController < BackofficeController
  skip_before_action :authenticate_admin!, only: :show

  def index
    @vehicles = Vehicle.all

    @services = Service.all

  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
    
    @vehicle = Vehicle.find(params[:id])

    @services = Service.select(:id, :price, :name)

    @selected_services = @vehicle.services.map{ |e| 
      JSON.parse(e).with_indifferent_access 
    }

    @selected_services_ids = @selected_services.map{ |e| e["id"] }
    render layout: "application"
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
    @services = Service.select(:id, :price, :name)

    @selected_services = @vehicle.services.map{ |e| 
      JSON.parse(e).with_indifferent_access 
    }

    @selected_services_ids = @selected_services.map{ |e| e["id"] }   
  end

  # GET /vehicles/1/edit
  def edit
    @services = Service.select(:id, :price, :name)    
    @vehicle = Vehicle.find(params[:id])
  
    @selected_services = @vehicle.services.map{ |e| 
      JSON.parse(e).with_indifferent_access 
    }

    @selected_services_ids = @selected_services.map{ |e| e["id"] }

  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)
    vehicle_params[:services] = Hash.new(vehicle_params[:services])
    if @vehicle.save
      redirect_to backoffice_vehicles_path, notice: "O Veículo #{@vehicle.plate} foi cadastrado com sucesso."
    else
      render :new
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    @vehicle = Vehicle.find(params[:id])
    if @vehicle.update(vehicle_params)
      redirect_to backoffice_vehicles_path, notice: "O Veículo #{@vehicle.plate} foi atualizado com sucesso."
    else
      render :edit
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
  	@vehicle = Vehicle.find(params[:id])
  	if @vehicle.present?
    	@vehicle.destroy
		end
      redirect_to backoffice_vehicles_path, notice: "O Veículo #{@vehicle.plate} foi deletado com sucesso."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:plate, :park_id, :total_to_pay, :permanence_type,:color , :model, :email, :observations, :payment_status, :services => [])
    end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"

  def pundit_user
  	current_admin
  end
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
end

app/helpers/backoffice/cash_flows_helper.rb
module Backoffice::CashFlowsHelper
end

app/helpers/backoffice/maps_helper.rb
module Backoffice::MapsHelper
end

app/helpers/backoffice/mensalists_helper.rb
module Backoffice::MensalistsHelper
end

app/helpers/backoffice/parks_helper.rb
module Backoffice::ParksHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/helpers/backoffice/send_mensalist_mail_helper.rb
module Backoffice::SendMensalistMailHelper
end

app/helpers/backoffice/services_helper.rb
module Backoffice::ServicesHelper
end

app/helpers/backoffice/vehicles_helper.rb
module Backoffice::VehiclesHelper
end

app/views/backoffice/mensalists/_form.html.erb
<%= form_for([:backoffice, @mensalist]) do |f| %>

  <%= f.label "Estacionamento" %>
  </br>
  <%= f.collection_select(:park_id, Park.all, :id, :park_name, {},{:class=>'form-control'} ) %>
  </br>
  <input type="hidden" id="data" value="<%= @park.to_json%>">
   
  <%= f.label "Nome" %>
  <%= f.text_field :name, class: 'form-control' %>
  </br>
  
  <%= f.label "Email" %>
  <%= f.text_field :email, class: 'form-control' %>
  </br>

  <%= f.label "Valor da mensalidade" %>
  <%= f.text_field :price, class: 'form-control', :style=>'width:30%' %>
  </br>

  <%= f.label "Data do primeiro pagamento" %>
  <br>
  <%= f.text_field :first_invoice_date, id: "datepicker" %>
  </br>
  <br>

  <%= f.label "Dias de tolerância" %>
  <br>
  <%= f.select(:days_of_tolerance, (0..30)) %> 
  </br>
  <br>

  <%= f.label "Placas" %>
  <%= f.text_field :plates, class: 'form-control' %>
  </br>

  <%= f.label "Quantidade de carros" %>
  <br>
  <%= f.select(:car_seat_numbers, (0..10)) %> 
  </br>
  <br>

  <h1>Serviços</h1>

  <% @services.each do |service| %>
    <%= f.label service.name %>
    <%= check_box_tag('mensalist[services][]', service.to_json, @selected_services_ids.include?(service.id)) %>
  <% end %>

 <!--  <h2>Serviços selecionados</h2>

  <% @selected_services.each do |service|  %>
    <%= service["name"] %><%= service["price"] * 3 %>
  <% end %> -->
</br>

  <br>
  <% if @mensalist.id %>
    <h1>Pagamento</h1>
      <%= f.label "Status do pagamento" %>
      <%= f.select :payment_status, enum_options_for_select(Mensalist, :payment_status) %>
    <br>
  <% end %>
  <br>

  </br>
  <%= link_to 'Voltar', backoffice_mensalists_path, class: "btn btn-primary" %>
  <%= f.submit "Salvar", class: "btn btn-primary" %>

<% end %>

app/views/backoffice/mensalists/edit.html.erb
  <div id="page-wrapper">
      <div class="container-fluid">
          <div class="row">
              <div class="col-lg-12">
                  <h2 class="page-header">Editar Mensalista</h2>
                    <div class="row">
                      <div class="col-lg-12">
                        <div class="panel panel-default">
                        <!-- /.panel-heading -->
                          <div class="panel-body">
                            <div class="col-md-5 col-md-offset-0">
                              <div class="row">
                
                        
                          <%= render 'form' %>

                            </div>      
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
          </div>

app/views/backoffice/mensalists/index.html.erb
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
             <div class="col-lg-12">
                <h2 class="page-header">Mensalistas</h2>

                    <% if notice %>
                        <div class="alert alert-success alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <%= notice %>
                        </div>
                    <% end %>
                
                <center>
                <%= link_to new_backoffice_mensalist_path, class: "btn btn-outline btn-primary btn-lg " do %>
                    Cadastrar Mensalistas
                <% end %>
                </center>
                <p></p>
            
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>Nome do mensalista</th>
                                        <th>Email</th>
                                        <th>Preço da mensalidade</th>
                                        <th>Data de cadastro</th>
                                        <th>Data de cobrança</th>
                                        <th>Preço total a pagar</th>
                                        <th>Status de Pagamento</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                  <% @mensalists.each do |mensalist| %>
                                  <%  @selected_services = mensalist.services.map{ |e| 
                                  JSON.parse(e).with_indifferent_access }%>
                                  <% if @selected_services && mensalist.price %>
                                  <% service_price = @selected_services.reduce(0) { |sum, x| sum += x[:price] } %>
                                  <% total = service_price + mensalist.price %> 
                                  <% end %>
                                  
                                    <tr class="odd gradeX">
                                        <td><%= mensalist.name %></td>
                                        <td><%= mensalist.email %></td>
                                        <td>R$ <%= mensalist.price %></td>
                                        <td><%= l mensalist.created_at, format: :short %></td>
                                        <% if mensalist.check_payment_status_and_update %>
                                          <td><%= mensalist.check_payment_status_and_update.strftime('%d/%m/%Y') %></td>
                                        <% else %>
                                          <td><%= mensalist.first_invoice_date.strftime('%d/%m/%Y') %></td>
                                        <% end %>
                                        <td>R$ <%= total %></td>
                                        <td><%= I18n.t :"activerecord.enums.mensalist.payment_statuses.#{mensalist.payment_status}" if mensalist.payment_status != nil %></td>
                                        <td style="width: 135px;">
                                            <%= link_to edit_backoffice_mensalist_path(mensalist), class: "btn btn-success btn-circle" do %>
                                                <i class="fa fa-edit"></i>
                                            <% end %>

                                            <%= link_to backoffice_mensalist_path(mensalist), method: :delete, class: "btn btn-danger btn-circle", data: { confirm: 'Tem certeza que deseja excluir?' } do %>
                                                <i class="fa fa-times"></i>
                                            <% end %>

                                            <% if mensalist.price %>
                                              
                                              <%= link_to backoffice_mensalist_path(mensalist.id), method: :get, class: "btn btn-info btn-circle" do %>
                                                  <i class="fa fa-tasks"></i>
                                              <% end %>
                                              <%= link_to edit_backoffice_send_mensalist_mail_path(mensalist), class: "btn btn-warning btn-circle", remote: true do %>
                                                <i class="fa fa-envelope"></i>
                                              <% end %>
                                            
                                            <% else %>
                                              <%= link_to '#', disabled: "disabled", class: "btn btn-info btn-circle" do %>
                                                <i class="fa fa-tasks"></i>
                                              <% end %>
                                              <%= link_to '#', disabled: "disabled", class: "btn btn-warning btn-circle" do %>
                                                <i class="fa fa-envelope"></i>
                                             <% end %>
                                            <% end %>
                                        </td>
                                    </tr>
                                  <% end %>
                                </tbody>
                            </table>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
                <!-- /.panel-body -->
                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->

<%= render partial: 'backoffice/mails/send_mail' %>

app/views/backoffice/mensalists/new.html.erb
  <div id="page-wrapper">
      <div class="container-fluid">
          <div class="row">
              <div class="col-lg-12">
                  <h2 class="page-header">Cadastro de Mensalistas</h2>
                    <div class="row">
                      <div class="col-lg-12">
                        <div class="panel panel-default">
                        <!-- /.panel-heading -->
                          <div class="panel-body">
                            <div class="col-md-5 col-md-offset-0">
                              <div class="row">
                
                        
                          <%= render 'form' %>

                            </div>      
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
          </div>

app/views/backoffice/mensalists/show.html.erb
  <style type="text/css" media="print">
@page {
    size: auto;   /* auto is the initial value */
    margin: 0;  /* this affects the margin in the printer settings */
}
</style>

  <div id="page-wrapper">
      <div class="container-fluid">
          <div class="row">
              <div class="col-lg-12">
                  <h2 class="page-header">Recibo da placa <%= @mensalist.name%> </h2>
                    <div class="row">
                      <div class="col-lg-12">
                        <div class="panel panel-default">
                        <!-- /.panel-heading -->
                          <div class="panel-body">
                            <div class="col-md-5 col-md-offset-0">
                              <div class="row">
                                Estacionamento: <%= @mensalist.park.park_name %>
                            <br>CNPJ: <%= @mensalist.park.park_cnpj %>
                            <br>Endereço: <%= @mensalist.park.park_location %>
                            <br>Placa(s) do(s) veículo(s): <%= @mensalist.plates %>

                            <br>Data da cobrança: <%= @mensalist.mensalist_receipt_date.strftime('%d/%m/%Y') %>
                            
                            <%  @selected_services = @mensalist.services.map{ |e| 
                                JSON.parse(e).with_indifferent_access }%>
                                <% if @selected_services && @mensalist.price %>
                                  <% service_price = @selected_services.reduce(0) { |sum, x| sum += x[:price] } %>
                                  <% total = service_price + @mensalist.price %> 
                                  <br>Serviços utilizados: <%= @selected_services.map{|data| data['name']}.join(', ').gsub(/["]/,' ') %>
                                  <br>Valor total: R$ <%= total %>
                                <% else %>
                                  <br>Valor total: R$ <%= @mensalist.price %>
                                <% end %>

                              <br>
                              <br>
                              <br>
                                <button id ="printbtn" class="btn btn-success" onclick="hidebtn()">Imprimir recibo</button>

                            </div>      
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
          </div>



<script>
function hidebtn() {
    window.print();
}
</script>